// Vairable format: MAXRESULT_COMPONENT_PAGENAME

export const MAXRESULT_SHOWCASE_HOME = 10
export const MAXRESULT_SHOWCASE_SECTION_CATEGORY = 18

export const MAXRESULT_TRACKS_ALBUM = 10
export const MAXRESULT_TRACKS_SINGLE = 5
