// Variable format: MAXRESULT_COMPONENT_PAGENAME
export default {
  MAXRESULT_SHOWCASE_HOME: 8,
  MAXRESULT_SHOWCASE_SECTION_CATEGORY: 18,

  MAXRESULT_HOME_LATEST_POSTS: 6,
  MAXRESULT_HOME_AUDIO_CHOICES: 6,

  MAXRESULT_TRACKS_ALBUM: 10,
  MAXRESULT_TRACKS_SINGLE: 10,

  MAXRESULT_ASIDEALBUMLIST_ALBUM: 5
}
